SHAREPOINT_TOKEN = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IktMWkZEb3hWVXpxNnVwTXZOcHhwZEo2VkRkWVNfUGl4bWU3NU9tc1RXSEkiLCJhbGciOiJSUzI1NiIsIng1dCI6IkNOdjBPSTNSd3FsSEZFVm5hb01Bc2hDSDJYRSIsImtpZCI6IkNOdjBPSTNSd3FsSEZFVm5hb01Bc2hDSDJYRSJ9"
SHAREPOINT_SITE_ID = "maqfiltros3.sharepoint.com,68b563be-e515-4193-9b5b-4dcf121342e8,347a1963-1db4-4613-8841-056a68baf7ec"
SHAREPOINT_LIST_ID = "418a9527-5b59-432e-8d95-bad94ef6aed1"
